"""entities.py — OKF bundle

Purpose:
    Entity resolution and auto-stub in <vault>/entities/.

Public:
    resolve_alias(name) -> Entity|None (searches frontmatter aliases
    across the bundle)
    ensure(slug, type, title) -> (Entity, created: bool)
    wikilink(entity) -> str
    card(entity) -> str (for `od who`)

Invariants:
    Slugs generated by od only (stable, lowercase, hyphenated); type is
    one of person/organization/system/project/topic; created stubs
    announced by caller via the created flag; never modifies an existing
    entity file.

Depends on:
    config, sections (frontmatter parsing), stdlib.
"""
