"""entities.py — OKF bundle

Purpose:
    Entity resolution and auto-stub in <vault>/entities/.

Public:
    resolve_alias(vault, name) -> Entity|None (searches frontmatter aliases
    across the bundle)
    ensure(vault, slug, type, title) -> (Entity, created: bool)
    wikilink(entity) -> str
    card(entity) -> str (for `od who`)
    slugify(text) -> str

Invariants:
    Slugs generated by od only (stable, lowercase, hyphenated); type is
    one of person/organization/system/project/topic; created stubs
    announced by caller via the created flag; never modifies an existing
    entity file.

Depends on:
    config, stdlib.

Notes:
    Module map lists sections for frontmatter parsing; sections has no
    frontmatter API yet. Entity YAML frontmatter is parsed here with a
    minimal subset sufficient for type/title/aliases/tags/org. Extract
    to sections only when a second consumer needs the same contract.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

from od import config

__all__ = [
    "EntitiesError",
    "AmbiguousEntity",
    "ENTITY_TYPES",
    "Entity",
    "slugify",
    "resolve_alias",
    "ensure",
    "wikilink",
    "card",
]

ENTITY_TYPES: frozenset[str] = frozenset(
    {
        "person",
        "organization",
        "system",
        "project",
        "topic",
    }
)

# Type -> subdirectory under entities/ (path is identity; matches usage
# example `people/michael-brumit.md`).
_TYPE_DIR: dict[str, str] = {
    "person": "people",
    "organization": "organizations",
    "system": "systems",
    "project": "projects",
    "topic": "topics",
}

_SLUG_RE = re.compile(r"[^a-z0-9]+")


class EntitiesError(Exception):
    """Raised when entity resolution or creation fails."""


class AmbiguousEntity(EntitiesError):
    """More than one entity matched the lookup name."""

    def __init__(self, name: str, matches: list[Entity]) -> None:
        self.name = name
        self.matches = matches
        paths = ", ".join(m.relpath for m in matches)
        super().__init__(f"ambiguous entity {name!r}; matches: {paths}")


@dataclass(frozen=True)
class Entity:
    """One OKF entity file under the vault entities bundle."""

    slug: str
    type: str
    title: str
    relpath: str
    aliases: tuple[str, ...] = ()
    tags: tuple[str, ...] = ()
    org: str | None = None
    abs_path: Path | None = None


def slugify(text: str) -> str:
    """Return a stable, lowercase, hyphenated slug for *text*.

    Non-alphanumeric runs become a single hyphen; leading/trailing hyphens
    are stripped. Empty input raises ``EntitiesError``.
    """
    if text is None or not str(text).strip():
        raise EntitiesError("cannot slugify empty text")
    lowered = str(text).strip().lower()
    slug = _SLUG_RE.sub("-", lowered).strip("-")
    if not slug:
        raise EntitiesError(f"slugify produced empty slug from {text!r}")
    return slug


def _vault_dir(vault: str) -> Path:
    """Resolve vault directory (name under vault_root, or filesystem path)."""
    if not vault or not str(vault).strip():
        raise EntitiesError("vault name must be non-empty")
    vault = str(vault).strip()
    cfg = config.load(vault, {})
    path = Path(vault).expanduser()
    if path.is_absolute() or len(path.parts) > 1:
        return path
    if not cfg.vault_root:
        raise EntitiesError(
            "vault_root is not set; cannot resolve vault "
            f"{vault!r} (set vault_root in ~/.config/od/config.toml)"
        )
    return Path(cfg.vault_root).expanduser() / vault


def _bundle_dir(vault: str) -> Path:
    """Return ``<vault>/<entities.dir>`` for *vault*."""
    cfg = config.load(vault, {})
    return _vault_dir(vault) / cfg.entities_dir


def _type_subdir(entity_type: str) -> str:
    if entity_type not in ENTITY_TYPES:
        raise EntitiesError(
            f"invalid entity type {entity_type!r}; "
            f"expected one of {sorted(ENTITY_TYPES)}"
        )
    return _TYPE_DIR[entity_type]


def _relpath_for(entity_type: str, slug: str, entities_dir: str) -> str:
    return f"{entities_dir}/{_type_subdir(entity_type)}/{slug}.md"


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def _parse_scalar(value: str) -> Any:
    value = value.strip()
    if value == "[]":
        return []
    if value == "~" or value == "null":
        return None
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [_unquote(part.strip()) for part in inner.split(",")]
    return _unquote(value)


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Parse a leading YAML frontmatter block into a dict and body.

    Minimal subset: ``key: value``, nested ``- list`` items under a key,
    inline ``[a, b]`` lists, quoted strings. Not a full YAML parser.
    """
    if not text.startswith("---\n") and text != "---":
        # Allow ---\\r\\n as well.
        if not text.startswith("---\r\n"):
            return {}, text

    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text

    meta: dict[str, Any] = {}
    i = 1
    current_list_key: str | None = None
    while i < len(lines):
        line = lines[i]
        if line.strip() == "---":
            rest = lines[i + 1 :]
            body = "\n".join(rest)
            if rest and text.endswith("\n") and not body.endswith("\n"):
                body += "\n"
            elif not rest and text.endswith("\n"):
                body = ""
            return meta, body

        if not line.strip():
            current_list_key = None
            i += 1
            continue

        list_item = re.match(r"^(\s+)-\s+(.*)$", line)
        if list_item and current_list_key is not None:
            meta.setdefault(current_list_key, [])
            if not isinstance(meta[current_list_key], list):
                meta[current_list_key] = []
            meta[current_list_key].append(_unquote(list_item.group(2)))
            i += 1
            continue

        kv = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$", line)
        if not kv:
            current_list_key = None
            i += 1
            continue

        key, raw_val = kv.group(1), kv.group(2)
        if raw_val == "":
            current_list_key = key
            meta[key] = []
        else:
            current_list_key = None
            meta[key] = _parse_scalar(raw_val)
        i += 1

    # No closing --- — treat as no frontmatter.
    return {}, text


def _string_list(value: Any) -> tuple[str, ...]:
    if value is None:
        return ()
    if isinstance(value, str):
        return (value,) if value else ()
    if isinstance(value, list):
        return tuple(str(v) for v in value if v is not None and str(v) != "")
    return (str(value),)


def _entity_from_file(path: Path, vault_dir: Path, entities_dir: str) -> Entity | None:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    meta, _body = parse_frontmatter(text)
    entity_type = meta.get("type")
    if not entity_type or str(entity_type) not in ENTITY_TYPES:
        return None
    entity_type = str(entity_type)
    slug = path.stem
    title = str(meta.get("title") or slug)
    try:
        rel = path.relative_to(vault_dir).as_posix()
    except ValueError:
        rel = path.as_posix()
    org_val = meta.get("org")
    org = None if org_val is None or org_val == "" else str(org_val)
    return Entity(
        slug=slug,
        type=entity_type,
        title=title,
        relpath=rel,
        aliases=_string_list(meta.get("aliases")),
        tags=_string_list(meta.get("tags")),
        org=org,
        abs_path=path,
    )


def _iter_entity_files(bundle: Path) -> Iterable[Path]:
    if not bundle.is_dir():
        return
    yield from sorted(bundle.rglob("*.md"))


def _load_all(vault: str) -> list[Entity]:
    vault_dir = _vault_dir(vault)
    cfg = config.load(vault, {})
    bundle = vault_dir / cfg.entities_dir
    entities: list[Entity] = []
    for path in _iter_entity_files(bundle):
        ent = _entity_from_file(path, vault_dir, cfg.entities_dir)
        if ent is not None:
            entities.append(ent)
    return entities


def _norm(name: str) -> str:
    return str(name).strip().casefold()


def resolve_alias(vault: str, name: str) -> Entity | None:
    """Resolve *name* to an entity via slug, title, or frontmatter aliases.

    Search is case-insensitive. Returns ``None`` if no match. Raises
    ``AmbiguousEntity`` when more than one entity matches.
    """
    if name is None or not str(name).strip():
        raise EntitiesError("lookup name must be non-empty")
    needle = _norm(name)
    matches: list[Entity] = []
    for ent in _load_all(vault):
        keys = {ent.slug, ent.title, *ent.aliases}
        if any(_norm(k) == needle for k in keys if k):
            matches.append(ent)
    if not matches:
        return None
    if len(matches) > 1:
        # Prefer exact slug match when unique among matches.
        slug_hits = [m for m in matches if _norm(m.slug) == needle]
        if len(slug_hits) == 1:
            return slug_hits[0]
        raise AmbiguousEntity(str(name).strip(), matches)
    return matches[0]


def _stub_text(entity_type: str, title: str, aliases: Iterable[str] = ()) -> str:
    alias_list = [a for a in aliases if a]
    lines = [
        "---",
        f"type: {entity_type}",
        f"title: {title}",
    ]
    if alias_list:
        lines.append("aliases:")
        for alias in alias_list:
            lines.append(f"  - {alias}")
    else:
        lines.append("aliases: []")
    lines.extend(["---", "", f"# {title}", ""])
    return "\n".join(lines)


def ensure(
    vault: str,
    slug: str,
    type: str,  # noqa: A002 — matches module-map public name
    title: str,
) -> tuple[Entity, bool]:
    """Ensure an entity file exists; never modify an existing file.

    Args:
        vault: Vault name or path.
        slug: File stem (od-owned; prefer ``slugify(title)``).
        type: One of ``ENTITY_TYPES``.
        title: Display title written into frontmatter and H1.

    Returns:
        ``(entity, created)`` where *created* is True only when a new stub
        was written. Callers announce creation on stderr.
    """
    entity_type = type
    if entity_type not in ENTITY_TYPES:
        raise EntitiesError(
            f"invalid entity type {entity_type!r}; "
            f"expected one of {sorted(ENTITY_TYPES)}"
        )
    if not slug or not str(slug).strip():
        raise EntitiesError("slug must be non-empty")
    if not title or not str(title).strip():
        raise EntitiesError("title must be non-empty")

    slug = str(slug).strip()
    # Reject path separators / traversal in slug.
    if slug != Path(slug).name or "/" in slug or "\\" in slug or slug in (".", ".."):
        raise EntitiesError(f"invalid slug {slug!r}")
    title = str(title).strip()

    cfg = config.load(vault, {})
    vault_dir = _vault_dir(vault)
    rel = _relpath_for(entity_type, slug, cfg.entities_dir)
    path = vault_dir / rel

    if path.is_file():
        ent = _entity_from_file(path, vault_dir, cfg.entities_dir)
        if ent is None:
            raise EntitiesError(
                f"entity file exists but is not a valid entity: {rel}"
            )
        return ent, False

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        # Exclusive create — never clobber if raced.
        fd = path.open("x", encoding="utf-8")
        try:
            fd.write(_stub_text(entity_type, title))
        finally:
            fd.close()
    except FileExistsError:
        ent = _entity_from_file(path, vault_dir, cfg.entities_dir)
        if ent is None:
            raise EntitiesError(
                f"entity file exists but is not a valid entity: {rel}"
            ) from None
        return ent, False
    except OSError as exc:
        raise EntitiesError(f"cannot create entity {rel}: {exc}") from exc

    ent = Entity(
        slug=slug,
        type=entity_type,
        title=title,
        relpath=rel,
        aliases=(),
        tags=(),
        org=None,
        abs_path=path,
    )
    return ent, True


def wikilink(entity: Entity) -> str:
    """Return an Obsidian wikilink for *entity* (``[[slug]]``)."""
    return f"[[{entity.slug}]]"


def card(entity: Entity) -> str:
    """Return a multi-line card for ``od who`` (stdout-friendly)."""
    lines = [
        entity.title,
        f"type: {entity.type}",
        f"slug: {entity.slug}",
        f"path: {entity.relpath}",
    ]
    if entity.aliases:
        lines.append("aliases: " + ", ".join(entity.aliases))
    else:
        lines.append("aliases: (none)")
    if entity.tags:
        lines.append("tags: " + ", ".join(entity.tags))
    if entity.org:
        lines.append(f"org: {entity.org}")
    return "\n".join(lines)
